#!/usr/bin/env bash

cd $(dirname $0)

(
if [ $# -eq 0 ]; then
  echo "--help"
else
  for i;
  do
    echo "'$i'"
  done
fi
) | xargs docker run --rm -v `pwd`:/tmp/screenshot -v /dev/shm:/dev/shm mokemokechicken/capture_web
